# YOUR API_KEY
# YOUR API_KEY_PRIMARY_VAL
# YOUR REQUEST_ID
API:
  HOST: "https://clovastudio.stream.ntruss.com"
  API_KEY: "YOUR API_KEY"
  API_KEY_PRIMARY_VAL: "YOUR API_KEY_PRIMARY_VAL"
  REQUEST_ID: "YOUR REQUEST_ID"

PARAMS:
  request_params:
    messages: preset_text
    topP: 0.7
    topK: 1
    maxTokens: 300
    temperature: 0.5
    repeatPenalty: 1.5
    stopBefore: []
    includeAiFilters: True
    seed: 0

PROMPT:
  preset_text:
    system: 
      role: "system"
      content: 
        '''
        당신은 한국어 글쓰기 어시스턴트입니다. 사용자의 현재 상황에 이입해서 가장 적절하게 메시지를 작성해주세요.

        사용자는 상황, 말투, 사용되는곳, 사용자가 추가적으로 원하는 요구사항 이렇게 네 가지에 대한 정보를 제시해줍니다. 당신은 이에 맞추어 메시지를 가장 적절하게 작성해주어야합니다.
        사용자의 입력 예시는 아래와 같습니다.
        상황: 업무를 보고할게요
        말투: 예의바르고 정중하게
        사용되는곳: 회사 메신저
        사용자가 추가적으로 원하는 요구사항: 부장님께 보고드려야하는 업무 현황. 부장님 심기에 거슬리는 표현은 쓰지 않을 것.
        
        추가 설명 없이 메시지만 출력해주세요.
        '''
      
    user:
      role: "user"