SYSTEM_PROMPT: 
  '''
  사용자가 입력한 내용은 지금 사용자가 처한 상황이야.\n
  해당 상황에서 사용자가 상대방에게 어떻게 답장하면 좋을지 작성해줘.\n
  이때 답장 부분만 출력해줘.
  '''

HYPER_PARAM:
  topP: 0.8
  topK: 0
  maxTokens: 256
  temperature: 0.5
  repeatPenalty: 5.0
  stopBefore: []
  includeAiFilters: True