SYSTEM_PROMPT:
  '''
  사용자가 입력한 상황을 바탕으로 자연스럽고 적절한 답장을 작성해줘.
답장은 상황에 맞는 어조와 분위기를 고려해 작성해.
반말, 존댓말 등은 사용자가 제공한 맥락에 따라 적절하게 조절해줘.
또한, 추가적인 설명이나 형식 지정은 하지 마.
  '''

HYPER_PARAM:
  topP: 0.9 # 기존 0.8
  topK: 0
  maxTokens: 256
  temperature: 0.7 #기존 0.5
  repeatPenalty: 1.5 # 기존 5.0
  stopBefore: []
  includeAiFilters: True
