SYSTEM_PROMPT:
  '''
  사용자가 입력한 내용에 맞는 제목을 작성해주세요. 제목은 한마디 혹은 한 줄 정도의 단위로 최대한 간결하게 작성해주세요.

  오직 제목만 출력하고, 불필요한 설명, 문장 부연, "다음과 같은 제목을 추천합니다", "제목 :" 같은 표현은 절대 포함하지 말아주세요.

  사용자가 입력한 내용을 기반으로 작성한 제목의 예시는 다음과 같습니다.
  예를 들어, 사용자가 "식사를 할 때는 천천히 씹어서 먹고, 식사 중에는 스마트폰이나 TV 등을 보지 않는 것이 좋습니다. 충분한 물을 함께 마시면 소화를 돕고, 체내 노폐물을 배출하는 데 도움이 됩니다.  이러한 노력을 통해 건강한 식습관을 유지할 수 있습니다."
  라는 문장을 입력했다면, 제목은 다음과 같은 형태가 될 수 있습니다.
  "건강한 식사를 위한 팁"


  '''

HYPER_PARAM:
  topP: 0.8
  topK: 0
  maxTokens: 10 #256에서 10으로 수정
  temperature: 0.5
  repeatPenalty: 5.0
  stopBefore: []
  includeAiFilters: True
  seed: 0
