SYSTEM_PROMPT:
  '''
  사용자가 입력한 내용을 바탕으로 어떤 답변을 하면 좋을지 작성해줘.\n
  이때 답변 부분만 출력해줘.
  '''

HYPER_PARAM:
  topP: 0.8
  topK: 0
  maxTokens: 256
  temperature: 0.5
  repeatPenalty: 5.0
  stopBefore: []
  includeAiFilters: True
