name: Deploy to Ncloud

on:
  push:
    branches: [ main ]

jobs:
  docker_image_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject .env file
        run: echo "${{ secrets.BACKEND_ENV }}" > ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ncloud 컨테이너 레지스트리 로그인 (Secrets에 설정된 값을 사용)
      - name: Login to Ncloud Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/dap-dap-back:latest
