name: Deploy to Ncloud

on:
  push:
    branches: [ main ]

jobs:
  docker_image_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject .env file
        run: echo "${{ secrets.BACKEND_ENV }}" > ./.env

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Ncloud Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/dap-dap-back:latest
          cache-from: type=registry,ref=${{ secrets.CONTAINER_REGISTRY_URL }}/dap-dap-back:buildcache
          cache-to: type=registry,ref=${{ secrets.CONTAINER_REGISTRY_URL }}/dap-dap-back:buildcache,mode=max


  pull_deploy:
    name: Connect server via SSH and update container
    needs: docker_image_push
    runs-on: ubuntu-latest
    steps:
      - name: Inject .env file
        run: echo "${{ secrets.BACKEND_ENV }}" > ./.env

      - name: Upload .env file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          source: ".env docker-compose.yml"
          target: "/home/${{ secrets.DEPLOYMENT_USERNAME }}/glee-back/"

      - name: Connect via SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          script: |
            # 올바른 디렉토리로 이동 후 실행
            cd /home/${{ secrets.DEPLOYMENT_USERNAME }}/glee-back/
          
            # 도커 로그인
            docker login ${{ secrets.CONTAINER_REGISTRY_URL }} --username ${{ secrets.NCP_ACCESS_KEY }} --password ${{ secrets.NCP_SECRET_KEY }}
            
            # 새로운 이미지 Pull
            docker pull ${{ secrets.CONTAINER_REGISTRY_URL }}/dap-dap-back:latest
            
            # 기존 컨테이너 종료 및 삭제
            docker-compose down || true

            # Docker Compose 실행 (환경 변수 적용)
            docker-compose up -d
            
            # 사용하지 않는 이미지 정리
            docker image prune -f
