name: Deploy to Ncloud

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ncloud 컨테이너 레지스트리 로그인 (Secrets에 설정된 값을 사용)
      - name: Login to Ncloud Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCLOUD_REGISTRY_URL }}
          username: ${{ secrets.NCLOUD_USERNAME }}
          password: ${{ secrets.NCLOUD_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.NCLOUD_REGISTRY_URL }}/your-project:latest
