  pull_deploy:
    name: Connect server via SSH and update container
    needs: docker_image_push
    runs-on: ubuntu-latest
    steps:
      - name: Inject .env file
        run: echo "${{ secrets.BACKEND_ENV }}" > ./.env

      - name: Upload .env file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          source: ".env"
          target: "/home/${{ secrets.DEPLOYMENT_USERNAME }}/glee-back/"

      - name: Connect via SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          script: |
            # 도커 로그인
            docker login ${{ secrets.CONTAINER_REGISTRY_URL }} --username ${{ secrets.NCP_ACCESS_KEY }} --password ${{ secrets.NCP_SECRET_KEY }}

            # 새로운 이미지 Pull
            docker pull ${{ secrets.CONTAINER_REGISTRY_URL }}/dap-dap-back:latest

            # 기존 컨테이너 종료 및 삭제
            docker stop dap-dap-back || true
            docker rm dap-dap-back || true

            # docker-compose.override.yml 생성 (몽고DB 환경 변수 추가)
            cat <<EOF > docker-compose.override.yml
            version: '3.8'
            services:
              mongodb:
                environment:
                  MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
                  MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            EOF

            # Docker Compose 실행 (환경 변수 적용)
            docker-compose up -d

            # 사용하지 않는 이미지 정리
            docker image prune -f
